[package]
name = "struct_to_array_derive"
version = "0.1.0"
edition = "2024"
authors = ["struct_to_array contributors"]
description = "Derive macro for struct_to_array"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bcolloran/struct_to_array"
documentation = "https://docs.rs/struct_to_array_derive"
readme = "../README.md"
keywords = ["struct", "array", "conversion", "derive", "macro"]
categories = ["data-structures", "no-std", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro-crate = "3"

[dev-dependencies]
pretty_assertions = "1"
